import Head from 'next/head';

import { GetGreeter, SetGreeter } from '../components/contract';
import { NavBar } from "../components/navigation";

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>dArchive</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <NavBar /> 
      
      <main
        style={{
          minHeight: '60vh',
          flex: '1',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <GetGreeter />
        <SetGreeter />
      </main>
    </div>
  );
}
